const { groq, MODELS, rateLimiter } = require("../config/groqClient");
const { chunkText, processChunksWithRateLimit } = require("./chunkingService");
const { checkPromptSafety } = require("./promptGuardService");

/**
 * PDF Structured Data Extractor Service
 * -------------------------------------
 * Educational Overview:
 * Large PDF documents (manuals, invoices, bank statements, reports) often contain 
 * thousands of words that exceed single LLM prompt token limits or 15K TPM rate limits.
 * 
 * Key Features:
 * 1. Security Guardrail: Passes document text through `meta-llama/llama-prompt-guard-2-86m`.
 * 2. Intelligent Text Chunking: Splits large PDF text into ~6,000 character (~1,500 token) chunks.
 * 3. Rate-Limited AI Extraction: Invokes Groq LLM sequentially for each chunk while respecting 30 RPM & 15K TPM.
 * 4. Result Aggregation: Combines JSON array records from all chunks into a unified dataset.
 */

/**
 * Helper function to extract structured JSON from a single text chunk
 */
async function extractChunkJSON(textChunk, chunkIndex, totalChunks) {
  // Check Prompt Guard 2 86M safety first
  const safetyCheck = await checkPromptSafety(textChunk);
  if (!safetyCheck.isSafe) {
    console.warn(`[PDFExtractor] Security warning on chunk ${chunkIndex + 1}:`, safetyCheck.reason);
  }

  const estimatedTokens = rateLimiter.estimateTokens(textChunk);
  
  // Enforce 30 RPM & 15K TPM wait if required
  await rateLimiter.waitIfNeeded(estimatedTokens);

  try {
    const completion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: `You are a data extraction expert. Extract structured data from the given text and return it in a JSON format that can be easily converted to CSV. 
          
          Guidelines:
          1. Identify key data points like names, dates, amounts, addresses, categories, items, etc.
          2. Create consistent column headers across records.
          3. Return data strictly as an array of objects.
          4. If data is tabular, preserve row and column structure.
          
          Example output format:
          [
            { "name": "John Doe", "email": "john@email.com", "amount": 150 }
          ]
          
          Return ONLY valid dry JSON array. No conversational text, no markdown.`,
        },
        {
          role: "user",
          content: `Extract structured data from this PDF text chunk (${chunkIndex + 1}/${totalChunks}) and return as JSON array:\n\n${textChunk}`,
        },
      ],
      model: MODELS.EXTRACTION,
      temperature: 0.1,
    });

    rateLimiter.recordUsage(estimatedTokens + 300);

    const result = completion.choices[0].message.content.trim();

    // Clean JSON response (handling markdown ```json ``` code fences if generated by LLM)
    const jsonMatch = result.match(/\[[\s\S]*\]/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }
    return JSON.parse(result);
  } catch (apiError) {
    console.warn(`[PDFExtractor] Groq AI extraction notice on chunk ${chunkIndex + 1}: ${apiError.message}. Using structured text fallback.`);
    // Fallback: Convert non-empty PDF lines into structured JSON rows
    const lines = textChunk.split(/\r?\n/).map(l => l.trim()).filter(l => l.length > 0);
    const fallbackRows = [];
    
    // Group lines into structured key-value object rows
    for (let i = 0; i < lines.length; i += 3) {
      fallbackRows.push({
        Field_1: lines[i] || "",
        Field_2: lines[i + 1] || "",
        Field_3: lines[i + 2] || "",
      });
    }
    return fallbackRows.length > 0 ? fallbackRows : [{ Text_Content: textChunk.slice(0, 500) }];
  }
}

/**
 * Main function to extract structured data from raw PDF text
 * @param {string} pdfText - Complete raw text extracted from PDF
 * @returns {Promise<Array<Object>>} Extracted JSON array of objects
 */
async function extractStructuredData(pdfText) {
  if (!pdfText || typeof pdfText !== "string" || pdfText.trim().length === 0) {
    throw new Error("No readable text could be extracted from the uploaded PDF file.");
  }

  try {
    // 1. Chunk PDF text into manageable blocks (~6,000 characters per chunk)
    const textChunks = chunkText(pdfText, 6000);
    console.log(`[PDFExtractor] Document contains ${pdfText.length} characters. Split into ${textChunks.length} chunk(s).`);

    if (textChunks.length === 1) {
      // Small PDF document: process directly
      return await extractChunkJSON(textChunks[0], 0, 1);
    }

    // 2. Multi-chunk PDF document: process sequentially with rate-limiting queue
    const combinedData = await processChunksWithRateLimit(
      textChunks,
      async (chunkTextStr, index, total) => {
        return await extractChunkJSON(chunkTextStr, index, total);
      }
    );

    console.log(`[PDFExtractor] Multi-chunk processing complete. Extracted ${combinedData.length} records in total.`);
    return combinedData;
  } catch (error) {
    console.error("[PDFExtractor] Error extracting structured data:", error);
    throw error;
  }
}

module.exports = { extractStructuredData };
